version: 3
jobs:
  checkout:
    docker:
      - image: liuchong/rustup:stable
        environment:
          OPENSSL_LIB_DIR: /usr/local/ssl
    steps:
      - checkout
  test:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run: cargo test

  build:
    docker:
      - image: scorpil/rust:stable
    steps:
      - checkout

      - run: cargo build --release

workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout