version: 2
jobs:
  checkout:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
  test:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run: cargo test

  build:
    docker:
      - image: liuchong/rustup:stable
    steps:
      - checkout
      - run: cargo build --release

workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
            